# Generated by Django 2.0.13 on 2019-07-10 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('IdPropuesta', models.AutoField(primary_key=True, serialize=False)),
                ('PropuestaNombre', models.CharField(max_length=500)),
                ('PropuestaDetalle', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaAprobada',
            fields=[
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('IdPropuestaAprobada', models.AutoField(primary_key=True, serialize=False)),
                ('PropuestaAprobadaNombre', models.CharField(max_length=500)),
                ('PropuestaAprobadaDetalle', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('codigo_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 7, 9, 23, 55, 11, 932921))),
                ('lugar_taller', models.CharField(max_length=60)),
                ('imagen', models.ImageField(default='img_talleres/ejemplo.jpg', upload_to='')),
            ],
        ),
    ]
