# Generated by Django 2.0.13 on 2019-07-10 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 0, 25, 59, 805500)),
        ),
    ]
