# Generated by Django 2.0.13 on 2019-07-10 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_auto_20190710_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 19, 43, 9, 628481)),
        ),
    ]
