# Generated by Django 2.0.13 on 2019-07-04 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_taller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestas',
            options={'ordering': ['vote_score']},
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 1, 32, 6, 663547)),
        ),
    ]
