# Generated by Django 2.0.13 on 2019-07-04 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0006_auto_20190704_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestas',
            options={},
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 1, 35, 58, 159913)),
        ),
    ]
