# Generated by Django 2.0.13 on 2019-07-09 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0008_auto_20190709_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(default='img_talleres/ejemplo.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 9, 19, 7, 46, 559252)),
        ),
    ]
